- name: "Docker SetUP"
  hosts: Docker
  tasks:
    - name: "Yum Configuration"
      yum_repository:
        name: "Docker"
        description: "Docker Packages"
        file: "docker"
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no
        
    - name: "Install Docker"
      package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present
        
    - name: "Start Docker Service"
      service:
        name: "docker"
        state: started
