- name: "My First Ansible Tower Task"
  hosts: all
  tasks:
    - name: "Debug task to print Govind Bhardwaj"
      debug:
        msg: "Govind Bhardwaj"
        
    - name: "u"
      command: id
      register: x
      
    - name: "User"
      debug:
        var: x
        
    - name: "Root Directory List"
      command: sudo ls /root/
      register: y
      
    - debug:
        var: y
