- name: "My First Ansible Tower Task"
  hosts: all
  tasks:
    - name: "Debug task to print Govind Bhardwaj"
      debug:
        msg: "Govind Bhardwaj"
        
    - name: "Make /root/JK/"
      command: mkdir /root/JK
